### ISSUE TITLE
Diskstation docker can not find python

### ISSUE THREAD

**Issue by dxh000130** [RetroPilot/retropilot-server#1]
![684C5124-3F49-4F0E-B4FC-10464EFD9987](https://user-images.githubusercontent.com/34475380/159989041-f6ef0595-ab1d-4cc8-987f-77ae1008c39b.jpeg)

**Comment by incognitojam** [comment]
I see that error too but it can be ignored. It's an issue with a dependency package as far as I can tell. If you wait longer does it continue to the next build steps?

**Comment by dxh000130** [comment]
Hi,
It can continue, but in the last step, it show ERROR: for retropilot_certbot_1  Cannot start service certbot: Bind mount failed: '/volume1/docker/retropilot/data/certbot/www' does not exists. I am not sure Is there a connection between the two questions.

**Comment by incognitojam** [comment]
We don't have the scope to help people setup their own production builds of retropilot-server, sorry. You need to configure the container volumes correctly for your own setup. Check in `docker-compose.uat.yml`.
